"""Airframe package → Gazebo SDF: the tags gz-sim actually reads.

Every assertion here is about *Gazebo's* dialect — which motor-plugin tags
gz-sim honours, and the fact that a joint must not carry a ``<pose>`` — so it
belongs with the compiler that emits it rather than with core.

The input used to be built by calling core's airframe presets and manifest
builder in-process.  It is now a checked-in package fixture
(``tests/fixtures/x500_package/manifest.json``, generated by core from
``x500_like()``).  That is the honest input: a manifest is a published format,
and this repository must compile one without importing the thing that wrote it.
"""

from __future__ import annotations

import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

from gazebo_bridge.package_to_sdf import compile_package_to_sdf

_FIXTURE = Path(__file__).resolve().parent / "fixtures" / "x500_package"


class TestSDFEmission(unittest.TestCase):
    """A quadrotor package in, SDF out, with the bug-fixed tags asserted."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.tree = ET.parse(compile_package_to_sdf(str(_FIXTURE)))

    def test_no_joint_pose_in_sdf(self) -> None:
        """Bug 5 regression: joint <pose> would double-offset the rotation axis."""
        for joint_el in self.tree.iter("joint"):
            self.assertIsNone(
                joint_el.find("pose"),
                f"Joint {joint_el.attrib.get('name')} must omit <pose> "
                "(SDF 1.10 default = child link frame, which is the joint origin)",
            )

    def test_motor_plugin_uses_motor_number_and_velocity(self) -> None:
        """Bugs C-7, C-8, C-9 regression: the gz-sim motor plugin tag set."""
        plugins = [
            p
            for p in self.tree.iter("plugin")
            if "MulticopterMotorModel" in (p.attrib.get("name") or "")
        ]
        self.assertEqual(len(plugins), 4)
        for p in plugins:
            self.assertIsNotNone(
                p.find("motorNumber"), "must use <motorNumber>, not <actuator_number>"
            )
            self.assertIsNone(
                p.find("actuator_number"), "<actuator_number> is the wrong tag for gz-sim"
            )
            self.assertIsNone(p.find("robotNamespace"), "<robotNamespace> breaks PX4 topic match")
            mt = p.find("motorType")
            self.assertIsNotNone(mt, "missing <motorType>velocity</motorType>")
            self.assertEqual(mt.text, "velocity")


if __name__ == "__main__":
    unittest.main()
